name: "CI"
on:
  push:
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: ${{ matrix.os }} build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v14
      with:
        extra_nix_config: |
          trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://hydra.iohk.io https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: shajra
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: cat ~/.config/nix/nix.conf
    - run: |
        nix --print-build-logs build \
        --arg checkMaterialization true \
        --file nix/ci.nix
    - run: |
        nix --print-build-logs path-info \
        --arg checkMaterialization true \
        --file nix/ci.nix
